#!/bin/bash
#SBATCH --job-name=L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229          # Name of the job
#SBATCH --time=7-00:00:00               # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=2               # Number of nodes
#SBATCH --ntasks=64
#SBATCH --clusters=draken
#SBATCH --output=/home/cluster_users/x_ilaria/MultiComponents_SC/Output/L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229/logs/log_L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229.o
#SBATCH --error=/home/cluster_users/x_ilaria/MultiComponents_SC/Output/L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229/logs/log_L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229.e


srun ../build/Release/GL_3components 16 /home/cluster_users/x_ilaria/MultiComponents_SC/Output/L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229 &> /home/cluster_users/x_ilaria/MultiComponents_SC/Output/L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229/logs/log_L16_a0_b1_eta1_e0.5_h5.4_bmin0.2245_bmax0.229.o



