#!/bin/bash
#SBATCH --job-name=L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1          # Name of the job
#SBATCH --time=1-00:00:00            # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=1               # Number of nodes
#SBATCH --ntasks=32
#SBATCH --output=/home/x_ilama/MultiComponents_SC/Output_3C/e_0.2/nu_0.5/h_5.4/L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1/logs/log_L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1.o
#SBATCH --error=/home/x_ilama/MultiComponents_SC/Output_3C/e_0.2/nu_0.5/h_5.4/L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1/logs/log_L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1.e

srun ../build/Release/GL_3component 12 /home/x_ilama/MultiComponents_SC/Output_3C/e_0.2/nu_0.5/h_5.4/L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1 /home/x_ilama/MultiComponents_SC/Output_3C/e_0.2/nu_0.5/h_5.4/L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1 0 &> /home/x_ilama/MultiComponents_SC/Output_3C/e_0.2/nu_0.5/h_5.4/L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1/logs/log_L12_a0_b1_eta1_e0.2_h5.4_nu0.5_bmin0.15_bmax0.5_init1.o


