#!/bin/bash
#SBATCH --job-name=L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0          # Name of the job
#SBATCH --time=1-00:00:00            # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=2               # Number of nodes
#SBATCH --ntasks=64
#SBATCH --output=/home/cluster_users/x_ilaria/MultiComponents_SC/Output_3C/e_0/nu_0.2/h_1/L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0/logs/log_L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0.o
#SBATCH --error=/home/cluster_users/x_ilaria/MultiComponents_SC/Output_3C/e_0/nu_0.2/h_1/L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0/logs/log_L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0.e

srun ../build/Release/GL_3component 10 /home/cluster_users/x_ilaria/MultiComponents_SC/Output_3C/e_0/nu_0.2/h_1/L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0 /home/cluster_users/x_ilaria/MultiComponents_SC/Output_3C/e_0/nu_0.2/h_1/L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0 0 &> /home/cluster_users/x_ilaria/MultiComponents_SC/Output_3C/e_0/nu_0.2/h_1/L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0/logs/log_L10_a0_b1_eta1_e0_h1_nu0.2_bmin2.0_bmax2.3_init0.o


